name: better-news
type: php
docroot: ""
no_project_mount: true
php_version: "8.2"
composer_version: "2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
    - v12.better-news
    - v13.better-news
additional_fqdns: []
use_dns_when_possible: true
